# Generated by Django 3.1.2 on 2022-08-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField(max_length=200)),
                ('tatuador', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
